- type: tickit.devices.source.Source
  name: source
  inputs: {}
  value: 10.0
- type: examples.devices.amplifier.Amplifier
  name: amp
  inputs:
    initial_signal:
      component: source
      port: value
  initial_amplification: 2
- type: tickit.devices.sink.Sink
  name: sink
  inputs:
    input:
      component: amp
      port: amplified_signal
