- tickit.devices.pneumatic.Pneumatic:
    name: filter1
    inputs: {}
    initial_speed: 0.5
    initial_state: False
    ioc_name: PNEUMATIC
    db_file: src/tickit/devices/pneumatic/db_files/filter1.db
- tickit.devices.sink.Sink:
    name: contr_sink
    inputs:
      input: filter1:output
