- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: []
    device:
      examples.devices.counter.Counter: {}
    inputs: {}
    name: counter
- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: []
    device:
      tickit.devices.sink.Sink: {}
    inputs:
      input: counter:value
    name: counter_sink
