- tickit.core.components.device_simulation.DeviceSimulation:
    adapters:
    - tickit.devices.cryostream.cryostream.CryostreamAdapter: {}
    device:
      tickit.devices.cryostream.cryostream.Cryostream: {}
    inputs: {}
    name: cryo
- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: []
    device:
      tickit.devices.toy.sink.Sink: {}
    inputs:
      input:
      - cryo
      - temperature
    name: contr_sink

