- tickit.core.components.device_simulation.DeviceSimulation:
    adapters:
    - tickit.devices.cryostream.cryostream.CryostreamAdapter:
        server_config:
          tickit.adapters.servers.tcp.TcpServer:
            format: JWI=
            host: localhost
            port: 25565
    config:
      tickit.devices.cryostream.cryostream.Cryostream: {}
    inputs: {}
    name: cryo
- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: []
    config:
      tickit.devices.toy.sink.Sink: {}
    inputs:
      input:
      - cryo
      - temperature
    name: contr_sink

