- tickit.devices.cryostream.Cryostream:
    inputs: {}
    name: cryo
#- tickit.core.components.device_simulation.DeviceSimulation:
#    adapters: []
#    device:
#      tickit.devices.sink.Sink: {}
#    inputs:
#      input: cryo:temperature
#    name: contr_sink

