- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: 
     - tickit.devices.femto.femto.FemtoAdapter: 
        db_file: record.db
    device:
      tickit.devices.femto.femto.Femto:
        name: "FEMTO"
        initial_gain: 2.5
        initial_current: 0.0
    inputs:
      input: current_device:output
    name: femto
- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: []
    device:
      tickit.devices.femto.femto.CurrentDevice:
        callback_period: 1000000000
    inputs: {}
    name: current_device