- examples.devices.http_device.ExampleHttpDevice:
    name: http-device
    inputs: {}
- examples.devices.zeromq_push_device.ExampleZeroMqPusher:
    name: zeromq-pusher
    inputs: 
        updates: http-device:updates
