- type: examples.devices.http_device.ExampleHttpDevice
  name: http-device
  inputs: {}
- type: examples.devices.zeromq_push_device.ExampleZeroMqPusher
  name: zeromq-pusher
  inputs:
      updates:
        component: http-device
        port: updates
