- tickit.devices.source.Source:
    name: source
    inputs: {}
    value: 42.0
- tickit.devices.examples.shutter.Shutter:
    name: shutter
    inputs:
      flux: source:value
    default_position: 0.2
    initial_position: 0.24
- tickit.devices.sink.Sink:
    name: sink
    inputs:
      flux: shutter:flux