- type: tickit.devices.source.Source
  name: source
  inputs: {}
  value: 42.0
- type: examples.devices.shutter.Shutter
  name: shutter
  inputs:
    flux:
      component: source
      port: value
  default_position: 0.2
  initial_position: 0.24
- type: tickit.devices.sink.Sink
  name: sink
  inputs:
    flux:
      component: shutter
      port: flux
