- !!python/object:tickit.devices.toy.string_controlled.StringControlledConfig
  adapters:
  - !!python/object:tickit.devices.toy.string_controlled.StringControlledAdapterConfig
    server_config: !!python/object:tickit.adapters.servers.tcp.TcpServerConfig
      host: localhost
      port: 25566
  inputs: {}
  name: tcp-contr
- !!python/object:tickit.devices.toy.sink.SinkConfig
  adapters: []
  inputs:
    input: !!python/tuple
    - tcp-contr
    - observed
  name: contr-sink
