- !!python/object:tickit.devices.toy.trampoline.RandomTrampolineConfig
  adapters: []
  callback_period: 1000000000
  inputs: {}
  name: rand-tramp
- !!python/object:tickit.devices.toy.sink.SinkConfig
  adapters: []
  inputs:
    input: !!python/tuple
    - rand-tramp
    - output
  name: tramp-sink
