- tickit.core.components.device_simulation.DeviceSimulation:
    adapters:
    - tickit.devices.toy.remote_controlled.RemoteControlledAdapter:
        server_config:
          tickit.adapters.servers.tcp.TcpServer:
            format: "%b\r\n"
    config:
      tickit.devices.toy.remote_controlled.RemoteControlled: {}
    inputs: {}
    name: tcp_contr
- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: []
    config:
      tickit.devices.toy.sink.Sink: {}
    inputs:
      input:
      - tcp_contr
      - observed
    name: contr_sink