- type: examples.devices.trampoline.RandomTrampoline
  name: rand_tramp
  inputs: {}
  callback_period: 1000000000
- type: tickit.devices.sink.Sink
  name: tramp_sink
  inputs:
    input:
      component: rand_tramp
      port: output
