- tickit.devices.toy.trampoline.RandomTrampoline:
    adapters: []
    callback_period: 1000000000
    inputs: {}
    name: rand_tramp
- tickit.devices.toy.sink.Sink:
    adapters: []
    inputs:
      input:
      - rand_tramp
      - output
    name: tramp_sink
