- examples.devices.remote_controlled.RemoteControlled:
    name: tcp_contr
    inputs: {}
    format: "%b\r\n"
- tickit.devices.sink.Sink:
    name: contr_sink
    inputs:
      input: tcp_contr:observed
