- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: []
    device:
      tickit.devices.toy.trampoline.RandomTrampoline:
        callback_period: 1000000000
    inputs: {}
    name: rand_tramp
- tickit.core.components.device_simulation.DeviceSimulation:
    adapters: []
    device:
      tickit.devices.toy.sink.Sink: {}
    inputs:
      input: rand_tramp:output
    name: tramp_sink
