- examples.devices.trampoline.RandomTrampoline:
    name: rand_tramp
    inputs: {}
    callback_period: 1000000000
- tickit.devices.sink.Sink:
    name: tramp_sink
    inputs:
      input: rand_tramp:output
