- type: examples.devices.remote_controlled.RemoteControlled
  name: tcp_contr
  inputs: {}
  format:
    format: "%b\r\n"
- type: tickit.devices.sink.Sink
  name: contr_sink
  inputs:
    input:
      component: tcp_contr
      port: observed
