- tickit.core.components.device_simulation.DeviceSimulation:
    adapters:
    - tickit.adapters.zmqadapter.ZeroMQAdapter: {}
    device:
      tickit.adapters.zmqadapter.ZMQStream: {}
    inputs: {}
    name: zeromq