name: Docs CI

on:
  push:
  pull_request:

jobs:
<<<<<<< HEAD
  build:
    name: "Docs CI"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install Packages
        # Can delete this if you don't use graphviz in your docs
        run: sudo apt-get install graphviz

      - name: Install Python Dependencies
        run: |
          pip install pipenv
          pipenv install --dev --deploy --python $(which python) && pipenv graph

      - name: Build Docs
        run: pipenv run docs

      - name: Move to versioned directory
        # e.g. master or 0.1.2
        run: mv build/html ".github/pages/${GITHUB_REF##*/}"

      - name: Publish Docs to gh-pages
        # Only master and tags are published
        if: "${{ github.repository_owner == 'dls-controls' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}"
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
=======
  docs:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Avoid git conflicts when tag and branch pushed at same time
        if: startsWith(github.ref, 'refs/tags')
        run: sleep 60

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Install system packages
        # Can delete this if you don't use graphviz in your docs
        run: sudo apt-get install graphviz

      - name: Install python packages
        uses: ./.github/actions/install_requirements
        with:
          requirements_file: requirements-dev-3.x.txt
          install_options: -e .[dev]

      - name: Build docs
        run: tox -e docs

      - name: Sanitize ref name for docs version
        run: echo "DOCS_VERSION=${GITHUB_REF_NAME//[^A-Za-z0-9._-]/_}" >> $GITHUB_ENV

      - name: Move to versioned directory
        run: mv build/html .github/pages/$DOCS_VERSION

      - name: Write switcher.json
        run: python .github/pages/make_switcher.py --add $DOCS_VERSION ${{ github.repository }} .github/pages/switcher.json

      - name: Publish Docs to gh-pages
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@64b46b4226a4a12da2239ba3ea5aa73e3163c75b # v3.9.1
>>>>>>> python3-pip-skeleton/main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/pages
          keep_files: true
